/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import {
  CheckSquare,
  Square,
  Copy,
  Check,
  Download,
  Filter,
  CheckCircle2,
} from 'lucide-react';
import { useDocumentContext } from '../context/DocumentContext';
import { LegalDisclaimer } from './LegalDisclaimer';

export const ChecklistView: React.FC = () => {
  const { checklistItems, toggleChecklistItem, activeDocument } = useDocumentContext();
  const [copied, setCopied] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState<string>('All');

  const categories = ['All', ...Array.from(new Set(checklistItems.map((c) => c.category)))];

  const filtered = checklistItems.filter(
    (item) => selectedCategory === 'All' || item.category === selectedCategory
  );

  const completedCount = checklistItems.filter((item) => item.completed).length;
  const progressPercent =
    checklistItems.length > 0 ? Math.round((completedCount / checklistItems.length) * 100) : 0;

  const handleCopyMarkdown = async () => {
    const lines = [
      `# Legal Review Checklist: ${activeDocument?.name || 'Document'}`,
      `Generated by LexiGuide AI\n`,
      ...checklistItems.map(
        (item) =>
          `- [${item.completed ? 'x' : ' '}] **[${item.priority}] ${item.task}** (${item.sourceClause})\n  ${item.explanation}`
      ),
      `\n*Disclaimer: For informational assistance only. Consult a qualified attorney.*`,
    ];

    try {
      await navigator.clipboard.writeText(lines.join('\n'));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.warn('Clipboard write failed');
    }
  };

  const getPriorityBadge = (priority: string) => {
    switch (priority) {
      case 'High':
        return 'bg-rose-50 text-rose-800 border-rose-200';
      case 'Medium':
        return 'bg-amber-50 text-amber-900 border-amber-200';
      default:
        return 'bg-slate-100 text-slate-700 border-slate-200';
    }
  };

  if (checklistItems.length === 0) {
    return (
      <div className="text-center py-16 bg-white rounded-2xl border border-slate-200 p-8 space-y-3">
        <CheckSquare className="w-8 h-8 text-slate-400 mx-auto" />
        <h3 className="text-base font-bold text-slate-900">No Checklist Items Available</h3>
        <p className="text-xs text-slate-500 max-w-sm mx-auto">
          Upload or analyze a legal document from the dashboard to generate an actionable pre-signing and compliance checklist.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header & Progress Bar */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-2xs space-y-4">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="space-y-1">
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold uppercase tracking-wider text-indigo-600 bg-indigo-50 px-2 py-0.5 rounded-sm">
                Action Items
              </span>
              <span className="text-xs text-slate-400">•</span>
              <span className="text-xs text-slate-500 font-medium">{checklistItems.length} Checklist Items</span>
            </div>
            <h2 className="text-xl font-bold text-slate-900 tracking-tight">Contract Review Checklist</h2>
            <p className="text-xs text-slate-600">
              Verify critical preconditions, required notices, fee verifications, and liability protections before signing.
            </p>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button
              id="copy-checklist-button"
              type="button"
              onClick={handleCopyMarkdown}
              className="flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold text-slate-700 bg-white border border-slate-300 rounded-xl hover:bg-slate-50 transition-colors shadow-2xs"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied Markdown' : 'Copy Checklist'}</span>
            </button>
          </div>
        </div>

        {/* Progress bar */}
        <div className="space-y-1.5 pt-2 border-t border-slate-100">
          <div className="flex items-center justify-between text-xs font-semibold">
            <span className="text-slate-700">Completion Progress</span>
            <span className="text-indigo-600">{completedCount} of {checklistItems.length} ({progressPercent}%)</span>
          </div>
          <div className="w-full h-2.5 bg-slate-100 rounded-full overflow-hidden">
            <div
              className="h-full bg-indigo-600 transition-all duration-300 rounded-full"
              style={{ width: `${progressPercent}%` }}
            />
          </div>
        </div>
      </div>

      {/* Category Pills */}
      <div className="flex items-center gap-1.5 overflow-x-auto pb-1">
        {categories.map((cat) => (
          <button
            key={cat}
            type="button"
            onClick={() => setSelectedCategory(cat)}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors ${
              selectedCategory === cat
                ? 'bg-slate-900 text-white'
                : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'
            }`}
          >
            {cat} {cat === 'All' ? `(${checklistItems.length})` : ''}
          </button>
        ))}
      </div>

      {/* Checklist Items */}
      <div className="space-y-3">
        {filtered.map((item) => (
          <div
            key={item.id}
            id={`checklist-item-${item.id}`}
            onClick={() => toggleChecklistItem(item.id)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === ' ' || e.key === 'Enter') {
                e.preventDefault();
                toggleChecklistItem(item.id);
              }
            }}
            className={`bg-white border rounded-xl p-4 sm:p-5 shadow-2xs cursor-pointer select-none transition-all flex items-start gap-3.5 ${
              item.completed
                ? 'border-emerald-200 bg-emerald-50/20 opacity-80'
                : 'border-slate-200 hover:border-slate-300'
            }`}
          >
            <div className="mt-0.5 text-indigo-600 shrink-0">
              {item.completed ? (
                <CheckCircle2 className="w-5 h-5 text-emerald-600" />
              ) : (
                <Square className="w-5 h-5 text-slate-400" />
              )}
            </div>

            <div className="space-y-1 min-w-0 flex-1">
              <div className="flex flex-wrap items-center gap-2">
                <span className={`text-[10px] font-bold uppercase px-2 py-0.5 rounded-md border ${getPriorityBadge(item.priority)}`}>
                  {item.priority} Priority
                </span>
                <span className="text-xs font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded-md">
                  {item.category}
                </span>
                <span className="text-xs text-slate-500 font-medium">{item.sourceClause}</span>
              </div>

              <h4
                className={`text-sm font-bold tracking-tight ${
                  item.completed ? 'line-through text-slate-500' : 'text-slate-900'
                }`}
              >
                {item.task}
              </h4>

              <p className="text-xs text-slate-600 leading-relaxed">{item.explanation}</p>
            </div>
          </div>
        ))}
      </div>

      <LegalDisclaimer compact />
    </div>
  );
};
